# Generated by Django 4.2.9 on 2024-12-01 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 12, 6, 7, 9, 42, 369412, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
