# Generated by Django 4.2.9 on 2024-11-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_customer_alter_factory_executors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='executors',
            new_name='customers',
        ),
    ]
