# Generated by Django 4.2.9 on 2024-11-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_categorymaterial_executor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='executor',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название заказа')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('material_name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.customer', verbose_name='Заказчик')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.executor', verbose_name='Исполнитель')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.categorymaterial', verbose_name='Категория материала')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
