# Generated by Django 4.2.9 on 2024-11-10 10:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_alter_customer_options_alter_executor_options_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
    ]
