# Generated by Django 4.2.9 on 2024-11-10 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_alter_order_customer_alter_order_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factory_orders', to='scrap.factory', verbose_name='Завод'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 15, 10, 24, 9, 170288, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
