# Generated by Django 4.2.9 on 2024-07-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Цех', 'verbose_name_plural': 'Цехи'},
        ),
    ]
