# Generated by Django 4.2.9 on 2024-08-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_birthday_alter_profile_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_head', to=settings.AUTH_USER_MODEL, verbose_name='Начальник цеха'),
        ),
    ]
