# Generated by Django 4.2.9 on 2024-11-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_workshop_head_remove_profile_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
    ]
